# Generated by Django 4.0.3 on 2022-03-23 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
